# Generated by Django 4.2.7 on 2025-11-17 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_phone_number_auth'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignupOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=255)),
                ('channel', models.CharField(choices=[('sms', 'SMS'), ('email', 'Email')], max_length=10)),
                ('otp', models.CharField(max_length=6)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='passwordresetotp',
            new_name='accounts_pa_phone_n_ccfadd_idx',
            old_name='accounts_pa_phone_n_123456_idx',
        ),
        migrations.AddIndex(
            model_name='signupotp',
            index=models.Index(fields=['identifier', 'channel'], name='accounts_si_identif_7f0cdf_idx'),
        ),
    ]
